services:
  jpmc:
    build:
      # context: . # remove me if launching from github package (not development)
      dockerfile: Dockerfile
    env_file:
      - .env
    port: 5000:5000
    command: ["python", "manage.py",  "runserver"]
    networks:
      - shared_network

networks:
  shared_network:
    external: true